chidieberen1999scrumy/urls.py
from django.urls import path, include

from . import views

app_name = "chidieberen1999scrumy"

urlpatterns = [
    path('', views.index, name='index'),
    path('movegoal/<int:goal_id>', views.move_goal, name='movegoal'),
    path('addgoal', views.add_goal, name='addgoal'),
    path('home', views.home, name='home'),
    path('logout', views.logout_view, name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),   
]

myscrumy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chidieberen1999scrumy/', include('chidieberen1999scrumy.urls', namespace='chidieberen1999scruny')),
    path('websocket/', include('websocket.urls')),
]

chidieberen1999scrumy/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class ScrumyGoals(models.Model):
    goal_id = models.IntegerField()
    goal_name = models.CharField(max_length=255)
    created_by = models.CharField(max_length=255)
    moved_by = models.CharField(max_length=255)
    owner = models.CharField(max_length=255)
    user = models.ForeignKey(User, related_name='user_goals', on_delete=models.CASCADE)
    goal_status = models.ForeignKey("GoalStatus", related_name="goals", on_delete=models.PROTECT)

    def __str__(self):
        return self.goal_name

class ScrumyHistory(models.Model):
    moved_by = models.CharField(max_length=255)
    created_by = models.CharField(max_length=255)
    moved_from = models.CharField(max_length=255)
    moved_to = models.CharField(max_length=255)
    time_of_action = models.DateTimeField()
    goal = models.ForeignKey("ScrumyGoals", on_delete=models.PROTECT)

    def __str__(self):
        return self.created_by
    
class GoalStatus(models.Model):
    status_name = models.CharField(max_length=255)

    def __str__(self):
        return self.status_name

chidieberen1999scrumy/forms.py
from .models import User, ScrumyGoals
from django.forms import ModelForm, Form
from django import forms 

class SignupForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password']


class CreateGoalForm(ModelForm):
    class Meta:
        model = ScrumyGoals
        fields = '__all__'


class MoveGoalForm(Form):
    choices = (('Daily Goal', 'Daily Goal'), ('Weekly Goal', 'Weekly Goal'), ('Done Goal', 'Done Goal'), ('Verify Goal', 'Verify Goal'))
    status_name = forms.ChoiceField(choices=choices)
    

chidieberen1999scrumy/views.py
from django.contrib.auth.models import Group
from django.contrib.auth.hashers import make_password
from django.contrib.auth import logout
from django.contrib import messages
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import ScrumyGoals, GoalStatus, User
from .forms import CreateGoalForm, SignupForm, MoveGoalForm
import random


def index(request):
    
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.password = make_password(form.cleaned_data['password'])
            new_user.save()

            developer_group = Group.objects.get(name="Developer")
            new_user = User.objects.get(username=form.cleaned_data['username'])
            developer_group.user_set.add(new_user)
            messages.success(request, 'Your account has been created sucessfully')
            return redirect('/chidieberen1999scrumy/accounts/login', permanent=True)
    else:
        form = SignupForm()

    return render(request, 'index.html', {'form':form})


def move_goal(request, goal_id):

    current_user = request.user

    dictionary = {
        'error': "A record with that goal id does not exist"
    }

    try:
        goal = ScrumyGoals.objects.get(goal_id=goal_id)
    except Exception as e:
        return render(request, 'exception.html', dictionary)
    
    if request.method == 'POST':
        form = MoveGoalForm(request.POST)
        if form.is_valid():

            if current_user.groups.filter(name="Developer").exists():
                if form.cleaned_data['status_name'] == "Done Goal":
                    messages.error(request, "you don't have sufficient permmissions to perform that action.")
                    return redirect('chidieberen1999scrumy:home', permanent=True)
                if goal.user != current_user:
                    messages.error(request, """you don't have sufficient permmissions to perform that action.
                    Try moving a goal you created""")
                    return redirect('chidieberen1999scrumy:home', permanent=True)

            if current_user.groups.filter(name="Quality Assurance").exists():
                if form.cleaned_data['status_name'] == "Weekly Goal":
                    messages.error(request, "you don't have sufficient permmissions to perform that action.")
                    return redirect('chidieberen1999scrumy:home', permanent=True)
                if goal.user != current_user and goal.goal_status.status_name != "Verify Goal":
                    messages.error(request, "You can only move goal's of others provided they have been verified")
                    return redirect('chidieberen1999scrumy:home', permanent=True)

            if current_user.groups.filter(name="Owner").exists():
                if goal.user != current_user:
                    messages.error(request, """you don't have sufficient permmissions to perform that action.
                    Try moving a goal you created""")
                    return redirect('chidieberen1999scrumy:home', permanent=True)

            goal.goal_status = GoalStatus.objects.get(status_name=form.cleaned_data['status_name'])
            goal.save()
            messages.success(request, f"The goal has been sucessfully moved to {form.cleaned_data['status_name']}")
            return redirect('chidieberen1999scrumy:home', permanent=True)
    else:
        form = MoveGoalForm()
    return render(request, 'movegoal.html', {'form':form})


def add_goal(request):

    current_user = request.user
    if request.method == "POST":
        form = CreateGoalForm(request.POST)
        if form.is_valid():
            form.save(commit=False)
            if current_user.groups.first().name in ["Developer", "Quality Assurance", "Owner"]:
                if form.cleaned_data['user'] != current_user or \
                    form.cleaned_data['goal_status'].status_name != "Weekly Goal":
                    messages.error(request, "You can only create a weekly goal for yourself")
                    return render(request, 'addgoal.html', {'form': form})
            form.save()
            messages.success(request, "Goal has been successfully created")
            return redirect('chidieberen1999scrumy:home', permanent=True)
    else:
        form = CreateGoalForm()

    return render(request, 'addgoal.html', {'form': form})


def home(request):
    data = {
        'users': User.objects.all(),
        'weekly': GoalStatus.objects.get(status_name="Weekly Goal").goals.all(),
        'daily': GoalStatus.objects.get(status_name="Daily Goal").goals.all(),
        'verify': GoalStatus.objects.get(status_name="Verify Goal").goals.all(),
        'done': GoalStatus.objects.get(status_name="Done Goal").goals.all()
    }
    return render(request, 'home.html', data)

def logout_view(request):
    logout(request)
    redirect('chidieberen1999scrumy:login', permanent=True)

chidieberen1999scrumy/templates/addgoal.html
<!DOCTYPE html>
<html>
    {% load static %}
    <head>
        <title>Add Goal</title>
        <link rel = "stylesheet" type = "text/css" href = "{% static 'form.css' %}" />
        <style>
            input[type=text], select {
              width: 100%;
              padding: 12px 20px;
              margin: 8px 0;
              display: inline-block;
              border: 1px solid #ccc;
              border-radius: 4px;
              box-sizing: border-box;
            }
            
            input[type=submit] {
              width: 100%;
              background-color: #4CAF50;
              color: white;
              padding: 14px 20px;
              margin: 8px 0;
              border: none;
              border-radius: 4px;
              cursor: pointer;
            }
            
            input[type=submit]:hover {
              background-color: #45a049;
            }
            
            div {
              border-radius: 5px;
              background-color: #f2f2f2;
              padding: 20px;
            }
            </style>
    </head>
    <body>
        <h2><a href="{% url 'chidieberen1999scrumy:home' %}">Home </a> <a href="{% url 'chidieberen1999scrumy:logout' %}">Logout</a></h2>
        <p>Currrent User: {{ request.user }}</p>
        <p>Groups: {{ request.user.groups.first }}</p><br>

        {% if messages %}
          <ul class="messages">
              {% for message in messages %}
                <li>{{ message }}</li>
              {% endfor %}
          </ul>
        {% endif %}
        <div>
            <form method="POST" action="">
                {% csrf_token %}
                {{ form }}
                <input type="submit" name="submit" value="Submit">
            </form>
        </div>
    </body>
</html>

chidieberen1999scrumy/templates/exception.html
<!DOCTYPE html>
<html>

<head>
    <title>Error</title>
</head>

<body>
    <p>{{ error }}</p>
</body>

</html>

chidieberen1999scrumy/templates/home.html
<!DOCTYPE html>
<html>

<head>
    <title>Home</title>
    <style>
        table, th, td {
          border: 1px solid black;
        }
    </style>
</head>

<body>

    <p>Currrent User: {{ request.user }}</p>
    <p>Groups: {{ request.user.groups.first }}</p><br>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <h2><a href="{% url 'chidieberen1999scrumy:addgoal' %}">Add Goal</a></h2>
    <h2><a href="{% url 'chidieberen1999scrumy:logout' %}">Logout</a></h2>
    <table>
        <tr>
            <th>User</th>
            <th>Weekly Goals</th>
            <th>Daily Goals</th>
            <th>Verify Goals</th>
            <th>Done Goals</th>
        </tr>
        
        {% for user in users %}
            <tr>
                <td>{{ user }}</td>
                <td>
                    {% for goal in weekly %}
                        {% if goal.user == user %}
                            <a href="{% url 'chidieberen1999scrumy:movegoal' goal_id=goal.goal_id %}"> {{ goal.goal_id }} {{goal.goal_name}} </a><br>
                        {% endif %} 
                    {% endfor %}
                </td>
                <td>
                    {% for goal in daily %}
                        {% if goal.user == user%}
                            <a href="{% url 'chidieberen1999scrumy:movegoal' goal.goal_id %}"> {{ goal.goal_id }} {{goal.goal_name}} </a><br>
                        {% endif %} 
                    {% endfor %}
                </td>
                <td>
                    {% for goal in verify %}
                        {% if goal.user == user%}
                            <a href="{% url 'chidieberen1999scrumy:movegoal' goal.goal_id %}"> {{ goal.goal_id }} {{goal.goal_name}} </a><br>
                        {% endif %} 
                    {% endfor %}
                </td>
                <td>
                    {% for goal in done %}
                        {% if goal.user == user%}
                            <a href="{% url 'chidieberen1999scrumy:movegoal' goal.goal_id %}"> {{ goal.goal_id }} {{goal.goal_name}} </a><br>
                        {% endif %} 
                    {% endfor %}
                </td>
            </tr>
                
        {% endfor %}
    </table>
</body>

</html>

chidieberen1999scrumy/templates/index.html
<!DOCTYPE html>
<html>
    {% load static %}
    <head>
        <title>Register</title>
        <link rel = "stylesheet" type = "text/css" href = "{% static 'form.css' %}" />
        <style>
            input[type=text], select {
              width: 100%;
              padding: 12px 20px;
              margin: 8px 0;
              display: inline-block;
              border: 1px solid #ccc;
              border-radius: 4px;
              box-sizing: border-box;
            }
            
            input[type=submit] {
              width: 100%;
              background-color: #4CAF50;
              color: white;
              padding: 14px 20px;
              margin: 8px 0;
              border: none;
              border-radius: 4px;
              cursor: pointer;
            }
            
            input[type=submit]:hover {
              background-color: #45a049;
            }
            
            div {
              border-radius: 5px;
              background-color: #f2f2f2;
              padding: 20px;
            }
            </style>
    </head>
    <body>
        <div>
            <form method="POST" action="">
                {% csrf_token %}
                {{ form }}
                <input type="submit" name="submit" value="Submit">
            </form>
        </div>
    </body>
</html>

chidieberen1999scrumy/templates/movegoal.html
<!DOCTYPE html>
<html>
    <head>
        <style>
            input[type=text], select {
              width: 100%;
              padding: 12px 20px;
              margin: 8px 0;
              display: inline-block;
              border: 1px solid #ccc;
              border-radius: 4px;
              box-sizing: border-box;
            }
            
            input[type=submit] {
              width: 100%;
              background-color: #4CAF50;
              color: white;
              padding: 14px 20px;
              margin: 8px 0;
              border: none;
              border-radius: 4px;
              cursor: pointer;
            }
            
            input[type=submit]:hover {
              background-color: #45a049;
            }
            
            div {
              border-radius: 5px;
              background-color: #f2f2f2;
              padding: 20px;
            }
        </style>
    </head>
    <body>
      <h2><a href="{% url 'chidieberen1999scrumy:home' %}">Home </a> <a href="{% url 'chidieberen1999scrumy:logout' %}">Logout</a></h2>
      <p>Currrent User: {{ request.user }}</p>
      <p>Groups: {{ request.user.groups.first }}</p><br>
        <div>
            <form action="" method="POST">
                {% csrf_token %}
                <p>Move to:</p><br>
                {{ form }}
                <input type="submit" name="submit" value="Submit">
            </form>
        </div>
    </body>
</html>